[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "pier", email = "piergiuseppe.mallozzi@gmail.com"},
]
dependencies = [
    "cairo-lang>=0.11.0.1",
]
requires-python = ">=3.9"
license = {text = "MIT"}
